version: "3.8"
services:
  cow-det-vid-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cow-det-vid-app
    ports:
      - "35235:5000"
    volumes:
      - .:/app
    restart: unless-stopped
